GET http://localhost:3001/room

###

GET http://localhost:3001/room/123

###

DELETE http://localhost:3001/room/1

###

GET http://localhost:3001/rtc/test/publisher/uid/pramodharya

###

GET http://localhost:3001/rtc/ping